### ISSUE TITLE
finished homework

### ISSUE THREAD

**Issue by florian4300** [htl-perg-2019-20-5ahif/highscore-exercise-florian4300#1]
@rstropek 

I did the homework with all the extra points challenges. You can find the docker-compose file here: https://hub.docker.com/repository/docker/florian4300/spacegame.
Of course it is also in the repository. 
You can find the deployed app under the following link:
https://spacegamehtlhomework.azurewebsites.net/
I deployed it with the help of my docker-compose file, because it did all the things automatically, if you get the ports right.

**Comment by rstropek** [comment]
Hi @florian4300!

Well done 👍! Today I found the time to take a close look. Just one minor thing: The deployed version looks for the web api on *localhost* -> deployed api missing. Nevertheless, well done, all points for you.

Greetings,
Rainer Stropek.
